name: Trigger auto deployment for user-authentication-testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/user-authentication-testing-AutoDeployTrigger-dd86d959-9fa1-4301-99e5-72ddfc1fc2aa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.USERAUTHENTICATIONTESTING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}sa
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.USERAUTHENTICATIONTESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERAUTHENTICATIONTESTING_REGISTRY_PASSWORD }}
          containerAppName: user-authentication-testing
          resourceGroup: SSE-movies
          imageToBuild: ghcr.io/user-authentication-testing:${{ github.sha }}
          
            

     

